apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ appName }}
  namespace: {{ namespace }}
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: {{ appName }}
  template:
    metadata:
      labels:
        app: {{ appName }}
    spec:
      containers:
      - name: {{ appName }}
        image: nginx:latest